version:  '3.9'

services:
  frontend:
    container_name: ecom-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /application/frontend
    volumes:
      - ./frontend:/application/frontend
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  backend:
    container_name: ecom-backend
    build: ./backend
    ports:
      - "3001:3001"
    working_dir: /application/backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
      - ./backend:/application/backend
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=bruebiel
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=databasepassword
      - APP_PORT=3001
    
  db:
    container_name: db
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=databasepassword
      - MYSQL_DATABASE=PSEL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: 'always'
    cap_add:
      - SYS_NICE
