version:  '3.9'

services:
  frontend:
    container_name: ecom-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app-frontend
    volumes:
      - ./frontend/src:/app-frontend/src
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  backend:
    container_name: ecom-backend
    build: ./backend
    ports:
      - "3001:3001"
    working_dir: /app-backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=bruebiel
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=databasepassword
      - APP_PORT=3001
    
  db:
    container_name: ecom-db
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=databasepassword
      - MYSQL_DATABASE=psel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: always
    cap_add:
      - SYS_NICE
